// Dados SAR JLE Telecom - Gerado em: 2026-08-28 09:00:10
// Fonte: Google Sheets (1kQyIsIDmsnunTbHU46n_3FmeL8ddbGGHnXHo6FXAfq4)
window.SAR_METADATA = {
    "total_records": 30,
    "generated_at": "2026-08-28 09:00:10",
    "source_file": "Google Sheets (1kQyIsIDmsnunTbHU46n_3FmeL8ddbGGHnXHo6FXAfq4)",
    "cidades": [
        "ESTRELA",
        "GRAVATAI",
        "PORTO ALEGRE",
        "TORRES",
        "TRAMANDAÍ",
        "VIAMÃO"
    ],
    "areas_tecnicas": [
        "BFMAA",
        "BFMAB",
        "BVSAB",
        "CLC",
        "CNTAA",
        "JITAB",
        "MNDAB",
        "MNDAC",
        "NAVAB",
        "PETAA",
        "STD",
        "TRA",
        "TRLAA",
        "UMBAA",
        "VIPAA",
        "VNVAA"
    ],
    "status_list": [
        "RELATÓRIO"
    ],
    "prazos": [
        "NO PRAZO",
        "ATRASADO"
    ],
    "competencias": [
        "AGOSTO/2025",
        "AGOSTO/2026",
        "DEZEMBRO/2025",
        "JANEIRO/2026",
        "JULHO/2025",
        "JULHO/2026",
        "JUNHO/2025",
        "NOVEMBRO/2025",
        "OUTUBRO/2025"
    ],
    "anos": [
        "2026",
        "2025"
    ],
    "meses": [
        "Janeiro",
        "Fevereiro",
        "Março",
        "Abril",
        "Maio",
        "Junho",
        "Julho",
        "Agosto",
        "Setembro",
        "Outubro",
        "Novembro",
        "Dezembro"
    ]
};

window.SAR_DATA = [
  {
    "cod": "RSCLER0623",
    "area_tecnica": "STD",
    "node": "",
    "site": "RSETA03",
    "cidade": "ESTRELA",
    "condominio": "",
    "endereco": "Rua Andre e Eidelwein,",
    "caixa_mdu": "STD.008.05.01",
    "classe_l": "",
    "classe_f": "MARCIEL",
    "situacao": "06/06/2025",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "6 ABERTURA E FECHAMENTO, 10 FUSÕES,",
    "data_entrada": "2025-06-06",
    "data_entrada_fmt": "06/06/2025",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2025-07-09",
    "data_entrega_fmt": "09/07/2025",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JUNHO/2025",
    "ano": "2025",
    "mes": "JUNHO",
    "mes_num": "06",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "ATRASADO",
    "tempo_dias": 23.0,
    "atraso_dias": 20.0
  },
  {
    "cod": "RSCLER0677",
    "area_tecnica": "CNTAA",
    "node": "",
    "site": "",
    "cidade": "GRAVATAI",
    "condominio": "",
    "endereco": "RUA JOÃO DUTRA, 81",
    "caixa_mdu": "CNTAA.051.M030",
    "classe_l": "",
    "classe_f": "ROGERIO",
    "situacao": "21/07/2025",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "",
    "data_entrada": "2025-07-21",
    "data_entrada_fmt": "21/07/2025",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2025-07-21",
    "data_entrega_fmt": "21/07/2025",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JULHO/2025",
    "ano": "2025",
    "mes": "JULHO",
    "mes_num": "07",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER0702",
    "area_tecnica": "VNVAA",
    "node": "",
    "site": "",
    "cidade": "PORTO ALEGRE",
    "condominio": "Cond Village Center Zona Sul",
    "endereco": "Av. da Cavalhada, 4760",
    "caixa_mdu": "VNVAA.051.01.07",
    "classe_l": "UBIRAJARA",
    "classe_f": "DIOGO",
    "situacao": "13/08/2025",
    "relatorio_foto": "206",
    "servico": "FOI LANÇADO 206 METROS DE CABO DE 12FO, COBRAE 27 METROS DE CORDOALHA DIELÉTRICA.",
    "data_entrada": "2025-08-13",
    "data_entrada_fmt": "13/08/2025",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2025-08-14",
    "data_entrega_fmt": "14/08/2025",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "AGOSTO/2025",
    "ano": "2025",
    "mes": "AGOSTO",
    "mes_num": "08",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 1.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER0703",
    "area_tecnica": "STD",
    "node": "",
    "site": "",
    "cidade": "ESTRELA",
    "condominio": "",
    "endereco": "Rua Dr Tostes, 33",
    "caixa_mdu": "STD.022.M080",
    "classe_l": "",
    "classe_f": "MARCIEL",
    "situacao": "11/08/2025",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "3 ABERTURAS E FECHAMENTO, 10 FUSÕES, 1 TESTES DE OTDR.",
    "data_entrada": "2025-08-11",
    "data_entrada_fmt": "11/08/2025",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2025-09-09",
    "data_entrega_fmt": "09/09/2025",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "AGOSTO/2025",
    "ano": "2025",
    "mes": "AGOSTO",
    "mes_num": "08",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "ATRASADO",
    "tempo_dias": 21.0,
    "atraso_dias": 18.0
  },
  {
    "cod": "RSCLER0711",
    "area_tecnica": "BVSAB",
    "node": "BVSAF",
    "site": "PAE NR",
    "cidade": "PORTO ALEGRE",
    "condominio": "",
    "endereco": "AL RAIMUNDO CORREA, 20",
    "caixa_mdu": "BVSAB.355.M030",
    "classe_l": "UBIRAJARA",
    "classe_f": "ANDERSON/GILSON/DIOGO",
    "situacao": "21/08/2025",
    "relatorio_foto": "357",
    "servico": "FOI LANÇADO 357 METROS DE CABO DE 12 FO, 3 ABERTURA E FECHAMENTO, 2 CX NOVA, 101 FUSÕES, 1 DERIVAÇÃO",
    "data_entrada": "2025-08-21",
    "data_entrada_fmt": "21/08/2025",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2025-08-22",
    "data_entrega_fmt": "22/08/2025",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "AGOSTO/2025",
    "ano": "2025",
    "mes": "AGOSTO",
    "mes_num": "08",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 1.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER0715",
    "area_tecnica": "STD",
    "node": "",
    "site": "RSETA03",
    "cidade": "ESTRELA",
    "condominio": "",
    "endereco": "RUA TIRADENTES 451",
    "caixa_mdu": "STD.022.M020",
    "classe_l": "",
    "classe_f": "",
    "situacao": "SEM LANÇAMENTO",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "",
    "data_entrada": null,
    "data_entrada_fmt": "-",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": null,
    "data_entrega_fmt": "-",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "NÃO INFORMADO",
    "ano": "NÃO INFORMADO",
    "mes": "NÃO INFORMADO",
    "mes_num": "",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "ATRASADO",
    "tempo_dias": 0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER0738",
    "area_tecnica": "CLC",
    "node": "",
    "site": "RSTES02",
    "cidade": "TORRES",
    "condominio": "",
    "endereco": "RUA BORGES DE MEDEIRO, 212",
    "caixa_mdu": "CLC022-M6",
    "classe_l": "MAQUENZE",
    "classe_f": "MAQUENZE",
    "situacao": "08/10/2025",
    "relatorio_foto": "",
    "servico": "",
    "data_entrada": "2025-10-08",
    "data_entrada_fmt": "08/10/2025",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": null,
    "data_entrega_fmt": "-",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "OUTUBRO/2025",
    "ano": "2025",
    "mes": "OUTUBRO",
    "mes_num": "10",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "ATRASADO",
    "tempo_dias": 232.0,
    "atraso_dias": 229.0
  },
  {
    "cod": "RSCLER0746",
    "area_tecnica": "TRLAA",
    "node": "",
    "site": "HUB ZONA SUL",
    "cidade": "PORTO ALEGRE",
    "condominio": "MIGRAÇÃO 144FO",
    "endereco": "HUB ZONA SUL",
    "caixa_mdu": "TRLAA.EST03",
    "classe_l": "BRUNO",
    "classe_f": "AUGUSTO",
    "situacao": "",
    "relatorio_foto": "1700",
    "servico": "FOI LANÇADO 1700 METROS DE CABO DE 144 AUTO SUSTENTAVEL E 220 METROS DE CABO PRECON, 36 METROS DE CORDOALHA, 2 DIO, 1 CX NOVA E 144 FUSÕES E 1 DERIVAÇÃO",
    "data_entrada": null,
    "data_entrada_fmt": "-",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": null,
    "data_entrega_fmt": "-",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "NÃO INFORMADO",
    "ano": "NÃO INFORMADO",
    "mes": "NÃO INFORMADO",
    "mes_num": "",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "ATRASADO",
    "tempo_dias": 0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER0752",
    "area_tecnica": "VIPAA",
    "node": "VIPAOA",
    "site": "RSPNO19",
    "cidade": "PORTO ALEGRE",
    "condominio": "Tree Haus By Porsche",
    "endereco": "Av. Veríssimo de Amaral, 536",
    "caixa_mdu": "VIPAA.041.M010",
    "classe_l": "",
    "classe_f": "DIOGO",
    "situacao": "12/11/2025",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "",
    "data_entrada": "2025-11-12",
    "data_entrada_fmt": "12/11/2025",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2025-11-13",
    "data_entrega_fmt": "13/11/2025",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "NOVEMBRO/2025",
    "ano": "2025",
    "mes": "NOVEMBRO",
    "mes_num": "11",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 1.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER0765",
    "area_tecnica": "VIPAA",
    "node": "VIPAPB",
    "site": "RSPNO19",
    "cidade": "PORTO ALEGRE",
    "condominio": "MANOBRA VISIUM (REPETTO)",
    "endereco": "AV TULIO DE ROSE 500",
    "caixa_mdu": "VIPAA.051.M010",
    "classe_l": "TIAGO FERREIRA",
    "classe_f": "MAURICIO",
    "situacao": "21/08/2026",
    "relatorio_foto": "",
    "servico": "",
    "data_entrada": "2026-08-21",
    "data_entrada_fmt": "21/08/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-08-21",
    "data_entrega_fmt": "21/08/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "AGOSTO/2026",
    "ano": "2026",
    "mes": "AGOSTO",
    "mes_num": "08",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER0783",
    "area_tecnica": "MNDAC",
    "node": "PBLAB",
    "site": "RSPSU02",
    "cidade": "PORTO ALEGRE",
    "condominio": "Estádio Beira-Rio",
    "endereco": "Av. Padre Cacique, 891",
    "caixa_mdu": "MNDAC.101.M010MAN",
    "classe_l": "",
    "classe_f": "DERIK / MARCOS EMILIANO",
    "situacao": "26/12/2025",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "16 ABERTURA E FECHAMENTO, 93 FUSÕES, 4 TESTES.COBRAR 130 METROS DE CABO DE 24FO A MAIS ,130 METROS DE DROP A MAIS E 1023 METROS DE CABO DE 12FO. E 130 METROS DE RETIRADA DE DROP, 3 DERIVAÇÕES.1 CX NOVA",
    "data_entrada": "2025-12-26",
    "data_entrada_fmt": "26/12/2025",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": null,
    "data_entrega_fmt": "-",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "DEZEMBRO/2025",
    "ano": "2025",
    "mes": "DEZEMBRO",
    "mes_num": "12",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "ATRASADO",
    "tempo_dias": 175.0,
    "atraso_dias": 172.0
  },
  {
    "cod": "RSCLER0792",
    "area_tecnica": "CLC",
    "node": "",
    "site": "RSTES02",
    "cidade": "TORRES",
    "condominio": "",
    "endereco": "R N SRA DOS NAVEGANTES 85",
    "caixa_mdu": "CLC024-M2",
    "classe_l": "",
    "classe_f": "MAQUENZE",
    "situacao": "22/01/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "",
    "data_entrada": "2026-01-22",
    "data_entrada_fmt": "22/01/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-01-25",
    "data_entrega_fmt": "25/01/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JANEIRO/2026",
    "ano": "2026",
    "mes": "JANEIRO",
    "mes_num": "01",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 1.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER0793",
    "area_tecnica": "TRA",
    "node": "",
    "site": "",
    "cidade": "TRAMANDAÍ",
    "condominio": "",
    "endereco": "R TUIUTI 413",
    "caixa_mdu": "TRA045.M030",
    "classe_l": "",
    "classe_f": "FABIO AMARILIO",
    "situacao": "22/01/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "",
    "data_entrada": "2026-01-22",
    "data_entrada_fmt": "22/01/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-01-26",
    "data_entrega_fmt": "26/01/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JANEIRO/2026",
    "ano": "2026",
    "mes": "JANEIRO",
    "mes_num": "01",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 2.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER0988",
    "area_tecnica": "UMBAA",
    "node": "",
    "site": "",
    "cidade": "VIAMÃO",
    "condominio": "Condomínio Residencial VIVER COOMETAL",
    "endereco": "Estr. Caminho do Meio, 4772",
    "caixa_mdu": "UMBAA.401/UMBAA.402",
    "classe_l": "CLEVERSON- FALTA 300 METROS PARA ESPINAR",
    "classe_f": "CLEVERSON",
    "situacao": "20/07/2026",
    "relatorio_foto": "4330",
    "servico": "FOI LANÇADO 520 METROS DE CABO AS, E 3810 METROS DE CABO DDS, COBRAR 2400 METROS DE CORDOALHA. 1 ABERTURA E FECHAMENTO, 3 CX NOVAS, 19 NAPS NOVAS, 4 DERIVAÇÕES, 122 FUSÕES,",
    "data_entrada": "2026-07-20",
    "data_entrada_fmt": "20/07/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-07-31",
    "data_entrega_fmt": "31/07/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JULHO/2026",
    "ano": "2026",
    "mes": "JULHO",
    "mes_num": "07",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "ATRASADO",
    "tempo_dias": 9.0,
    "atraso_dias": 6.0
  },
  {
    "cod": "RSCLER1005",
    "area_tecnica": "BFMAA",
    "node": "",
    "site": "RSPLE78",
    "cidade": "PORTO ALEGRE",
    "condominio": "RAMIRO BARCELOS 1215",
    "endereco": "RAMIRO BARCELOS 1215",
    "caixa_mdu": "BFMAA.071.M010",
    "classe_l": "",
    "classe_f": "CATIA",
    "situacao": "29/07/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "4 ABERTURA E FECHAMENTO, 5 FUSÕES, 3 TESTES, 2 TESTES OTDR.",
    "data_entrada": "2026-07-29",
    "data_entrada_fmt": "29/07/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-07-30",
    "data_entrega_fmt": "30/07/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JULHO/2026",
    "ano": "2026",
    "mes": "JULHO",
    "mes_num": "07",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 1.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER1006",
    "area_tecnica": "BFMAB",
    "node": "RBRAI",
    "site": "RSPCE13",
    "cidade": "PORTO ALEGRE",
    "condominio": "Edifício Castro Alves",
    "endereco": "R CASTRO ALVES 607",
    "caixa_mdu": "BFMAB.182.M020",
    "classe_l": "",
    "classe_f": "CATIA",
    "situacao": "29/07/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "2 ABERTURA E FECHAMENTO, 2 FUSÕES, 1 TESTE, 1 OTDR.",
    "data_entrada": "2026-07-29",
    "data_entrada_fmt": "29/07/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-07-29",
    "data_entrega_fmt": "29/07/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JULHO/2026",
    "ano": "2026",
    "mes": "JULHO",
    "mes_num": "07",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER1050",
    "area_tecnica": "JITAB",
    "node": "JITAIA",
    "site": "RSPNO75",
    "cidade": "PORTO ALEGRE",
    "condominio": "",
    "endereco": "Rua Joaquim G De Campos Netto, 35",
    "caixa_mdu": "JITAB.153.M070",
    "classe_l": "",
    "classe_f": "CATIA",
    "situacao": "30/07/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "8 ABERTURA E FECHAMENTO, 13 FUSÕES, 4 TESTES OTDR, 3 TESTES.",
    "data_entrada": "2026-07-30",
    "data_entrada_fmt": "30/07/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-07-31",
    "data_entrega_fmt": "31/07/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JULHO/2026",
    "ano": "2026",
    "mes": "JULHO",
    "mes_num": "07",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 1.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER0999",
    "area_tecnica": "BFMAA",
    "node": "BFMACA",
    "site": "PAE IND",
    "cidade": "PORTO ALEGRE",
    "condominio": "EDIFICIO CARAIBA",
    "endereco": "R OSVALDO ARANHA 232",
    "caixa_mdu": "(BFMAA.141.M020)",
    "classe_l": "",
    "classe_f": "CATIA",
    "situacao": "31/07/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "2 ABERTURA E FECHAMENTO, 4 FUSÕES, 2 TESTES, 2 TESTES OTDR.",
    "data_entrada": "2026-07-31",
    "data_entrada_fmt": "31/07/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-07-31",
    "data_entrega_fmt": "31/07/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JULHO/2026",
    "ano": "2026",
    "mes": "JULHO",
    "mes_num": "07",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER1000",
    "area_tecnica": "PETAA",
    "node": "",
    "site": "RSPLE11",
    "cidade": "PORTO ALEGRE",
    "condominio": "Cond. Edifício Dora",
    "endereco": "AV PROTASIO ALVES 3210",
    "caixa_mdu": "PETAA.153.M040",
    "classe_l": "TIAGO FERREIRA",
    "classe_f": "CATIA",
    "situacao": "31/07/2026",
    "relatorio_foto": "458",
    "servico": "5 ABERTURA E FECHAMENTO, 17 FUSÕES, 1 CX NOVA, 1 DERIVAÇÃO, 4 TESTES OTDR, 8 TESTES.",
    "data_entrada": "2026-07-31",
    "data_entrada_fmt": "31/07/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-08-04",
    "data_entrega_fmt": "04/08/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JULHO/2026",
    "ano": "2026",
    "mes": "JULHO",
    "mes_num": "07",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 2.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER1001",
    "area_tecnica": "PETAA",
    "node": "",
    "site": "RSPLE11",
    "cidade": "PORTO ALEGRE",
    "condominio": "ED MONTENEGRO",
    "endereco": "AV PROTASIO ALVES 3020",
    "caixa_mdu": "PETAA.153.M041",
    "classe_l": "",
    "classe_f": "CATIA",
    "situacao": "31/07/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "",
    "data_entrada": "2026-07-31",
    "data_entrada_fmt": "31/07/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-08-04",
    "data_entrega_fmt": "04/08/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JULHO/2026",
    "ano": "2026",
    "mes": "JULHO",
    "mes_num": "07",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 2.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER1002",
    "area_tecnica": "PETAA",
    "node": "",
    "site": "RSPLE11",
    "cidade": "PORTO ALEGRE",
    "condominio": "ED MONTENEGRO",
    "endereco": "AV PROTASIO ALVES 3032",
    "caixa_mdu": "PETAA.153.M042",
    "classe_l": "",
    "classe_f": "CATIA",
    "situacao": "31/07/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "",
    "data_entrada": "2026-07-31",
    "data_entrada_fmt": "31/07/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-08-04",
    "data_entrega_fmt": "04/08/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JULHO/2026",
    "ano": "2026",
    "mes": "JULHO",
    "mes_num": "07",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 2.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER1003",
    "area_tecnica": "PETAA",
    "node": "",
    "site": "RSPLE11",
    "cidade": "PORTO ALEGRE",
    "condominio": "ED MONTENEGRO",
    "endereco": "AV PROTASIO ALVES 3062",
    "caixa_mdu": "PETAA.153.M043",
    "classe_l": "",
    "classe_f": "CATIA",
    "situacao": "31/07/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "",
    "data_entrada": "2026-07-31",
    "data_entrada_fmt": "31/07/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-08-04",
    "data_entrega_fmt": "04/08/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JULHO/2026",
    "ano": "2026",
    "mes": "JULHO",
    "mes_num": "07",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 2.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER1004",
    "area_tecnica": "BFMAB",
    "node": "RBRAH",
    "site": "RSPCE13",
    "cidade": "PORTO ALEGRE",
    "condominio": "Edificio Prado",
    "endereco": "R MOSTARDEIRO 539",
    "caixa_mdu": "BFMAB.164.M30",
    "classe_l": "",
    "classe_f": "CATIA",
    "situacao": "31/07/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "2 ABERTURA E FECHAMENTO, 1 FUSÃO, 1 TESTE.",
    "data_entrada": "2026-07-31",
    "data_entrada_fmt": "31/07/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-07-03",
    "data_entrega_fmt": "03/07/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JULHO/2026",
    "ano": "2026",
    "mes": "JULHO",
    "mes_num": "07",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER1013",
    "area_tecnica": "BFMAA",
    "node": "FLOAPB",
    "site": "RSPLE78",
    "cidade": "PORTO ALEGRE",
    "condominio": "DOM CAMILO",
    "endereco": "R CDOR AZEVEDO 464",
    "caixa_mdu": "BFMAA.033.M030",
    "classe_l": "",
    "classe_f": "CATIA",
    "situacao": "31/07/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "2 ABERTURA E FECHAMENTO, 6 FUSÕES, 3 TESTES, 3 TESTES OTDR.",
    "data_entrada": "2026-07-31",
    "data_entrada_fmt": "31/07/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-07-31",
    "data_entrega_fmt": "31/07/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "JULHO/2026",
    "ano": "2026",
    "mes": "JULHO",
    "mes_num": "07",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER1009",
    "area_tecnica": "PETAA",
    "node": "",
    "site": "RSPLE11",
    "cidade": "PORTO ALEGRE",
    "condominio": "ED MILENE",
    "endereco": "AV PROTASIO ALVES 2468",
    "caixa_mdu": "PETAA.156.M020",
    "classe_l": "",
    "classe_f": "CATIA",
    "situacao": "03/08/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "5 ABERTURA E FECHAMENTO, 6 FUSÕES, 2 TESTES OTDR, 1 TESTE.",
    "data_entrada": "2026-08-03",
    "data_entrada_fmt": "03/08/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-08-04",
    "data_entrega_fmt": "04/08/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "AGOSTO/2026",
    "ano": "2026",
    "mes": "AGOSTO",
    "mes_num": "08",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 1.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER1010",
    "area_tecnica": "PETAA",
    "node": "",
    "site": "RSPLE11",
    "cidade": "PORTO ALEGRE",
    "condominio": "ED TARASCONE",
    "endereco": "AV PROTASIO ALVES 3560",
    "caixa_mdu": "PETAA.063.M020",
    "classe_l": "",
    "classe_f": "CATIA",
    "situacao": "04/08/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "2 ABERTURA E FECHAMENTO, 4 FUSÕES, 2 TESTES, 2 TESTES OTDR.",
    "data_entrada": "2026-08-04",
    "data_entrada_fmt": "04/08/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-08-04",
    "data_entrega_fmt": "04/08/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "AGOSTO/2026",
    "ano": "2026",
    "mes": "AGOSTO",
    "mes_num": "08",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER1011",
    "area_tecnica": "MNDAC",
    "node": "mndamb",
    "site": "RSPSU02",
    "cidade": "PORTO ALEGRE",
    "condominio": "Edifício Monroe",
    "endereco": "R MONROE 67",
    "caixa_mdu": "MNDAC.111.M020",
    "classe_l": "",
    "classe_f": "CATIA",
    "situacao": "04/08/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "3 ABERTURA E FECHAMENTO, 3 FUSÕES, 1 TESTE, 2 OTDR.",
    "data_entrada": "2026-08-04",
    "data_entrada_fmt": "04/08/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-08-05",
    "data_entrega_fmt": "05/08/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "AGOSTO/2026",
    "ano": "2026",
    "mes": "AGOSTO",
    "mes_num": "08",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 1.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER1047",
    "area_tecnica": "NAVAB",
    "node": "",
    "site": "",
    "cidade": "PORTO ALEGRE",
    "condominio": "ED SIMONE",
    "endereco": "R MARQUES DO ALEGRETE 291",
    "caixa_mdu": "NAVAB.043.M050",
    "classe_l": "TIAGO FERREIRA",
    "classe_f": "CATIA",
    "situacao": "04/08/2026",
    "relatorio_foto": "150",
    "servico": "FOI LANÇADO 150 METROS DE CABO DE 12FO, 4 ABERTURA E FECHAMENTO, 14 FUSÕES,1 DERIVAÇÃO,1 CX NOVA, 6 TESTE OTDR, 2 TESTES.",
    "data_entrada": "2026-08-04",
    "data_entrada_fmt": "04/08/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-08-06",
    "data_entrega_fmt": "06/08/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "AGOSTO/2026",
    "ano": "2026",
    "mes": "AGOSTO",
    "mes_num": "08",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 2.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER1049",
    "area_tecnica": "MNDAB",
    "node": "",
    "site": "",
    "cidade": "PORTO ALEGRE",
    "condominio": "",
    "endereco": "RUA LOPO GONÇALVES 235",
    "caixa_mdu": "MNDAB.035.M030",
    "classe_l": "TIAGO FERREIRA",
    "classe_f": "CATIA",
    "situacao": "19/08/2026",
    "relatorio_foto": "110",
    "servico": "",
    "data_entrada": "2026-08-19",
    "data_entrada_fmt": "19/08/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-08-22",
    "data_entrega_fmt": "22/08/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "AGOSTO/2026",
    "ano": "2026",
    "mes": "AGOSTO",
    "mes_num": "08",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 2.0,
    "atraso_dias": 0
  },
  {
    "cod": "RSCLER1053",
    "area_tecnica": "MNDAB",
    "node": "",
    "site": "",
    "cidade": "PORTO ALEGRE",
    "condominio": "REANÁLISE",
    "endereco": "RUA LOPO GONÇALVES 235.",
    "caixa_mdu": "MNDAB.352.M090",
    "classe_l": "",
    "classe_f": "MAURICIO",
    "situacao": "27/08/2026",
    "relatorio_foto": "SEM LANÇAMENTO",
    "servico": "",
    "data_entrada": "2026-08-27",
    "data_entrada_fmt": "27/08/2026",
    "data_inicio": null,
    "data_inicio_fmt": "-",
    "data_previsao": null,
    "data_previsao_fmt": "-",
    "data_entrega": "2026-08-27",
    "data_entrega_fmt": "27/08/2026",
    "data_medicao": null,
    "data_medicao_fmt": "-",
    "num_wf": "",
    "status_wf": "",
    "competencia": "AGOSTO/2026",
    "ano": "2026",
    "mes": "AGOSTO",
    "mes_num": "08",
    "status": "RELATÓRIO",
    "status_relatorio": "",
    "status_medicao": "",
    "status_obra": "Em Andamento",
    "prazo": "NO PRAZO",
    "tempo_dias": 0,
    "atraso_dias": 0
  }
];
