window.TECNODRILL_DATA = {
    "generated_at":  "2026-09-01 15:04:33",
    "empresa":  "Tecnodrill",
    "categories_origin":  {
                              "entradas":  [
                                               "Entrada",
                                               "Vendas",
                                               "Cobranças",
                                               "Empréstimo / Injeção de Dinheiro",
                                               "Rendimentos de Juros",
                                               "Restituição de Impostos",
                                               "Outros Recebimentos",
                                               "Transferência entre contas"
                                           ],
                              "saidas":  [
                                             "Saída",
                                             "13º Salário",
                                             "Ação Trabalhista",
                                             "Advogado",
                                             "Água",
                                             "Alimentação",
                                             "Aluguel",
                                             "Aplicação/Rentabilidade",
                                             "Assinaturas e Mensalidades",
                                             "Assistência Médica",
                                             "Benefícios Folha de Pagamento",
                                             "Bens de valor irrelevante",
                                             "Capital de Giro",
                                             "Cartão de Crédito",
                                             "Combustíveis",
                                             "Confraternização Funcionários",
                                             "Consórcios",
                                             "Contabilidade",
                                             "Contribuição Sindical",
                                             "Correio",
                                             "Custas de cartório",
                                             "Desenvolvimento Web",
                                             "Despachante",
                                             "Despesas Bancárias",
                                             "Despesas com Veículos/Documentos",
                                             "Despesas Diversas",
                                             "Despesas Financeiras",
                                             "Despesas Operacionais",
                                             "Domínio E Hospedagem Da Web",
                                             "Empréstimo Pessoal",
                                             "Empréstimos Bancários",
                                             "Encargos Bancários",
                                             "Endomarketing",
                                             "Energia Elétrica",
                                             "EPIs",
                                             "Estacionamento",
                                             "Estadias",
                                             "Férias",
                                             "Ferramentas",
                                             "FGTS",
                                             "Financiamento Veículos",
                                             "Folha De Pagamento",
                                             "Fornecedores",
                                             "Frete",
                                             "Imobilizado",
                                             "Impostos",
                                             "Impostos MEI",
                                             "Impostos Sobre a Folha De Pagamento / Benefícios",
                                             "Impressão",
                                             "INSS a Recolher",
                                             "Internet",
                                             "Investimentos",
                                             "Licenças / Licenças",
                                             "Locação de Equipamentos",
                                             "Manut. De Veículos",
                                             "Manutenção Predial",
                                             "Material de Copa e Cozinha",
                                             "Material de Escritório",
                                             "Material de Limpeza",
                                             "Material de Uso e Consumo",
                                             "Material utilizado em serviços",
                                             "Medicina do Trabalho",
                                             "Multas de transito",
                                             "Novo CNPJ",
                                             "Outros Pagamentos",
                                             "Passagens",
                                             "Pedágio",
                                             "Prestadores de Serviços",
                                             "Publicidade",
                                             "Refeição",
                                             "Rescisão",
                                             "Retiradas Sócios",
                                             "Seguro",
                                             "Taxas de Aluguel",
                                             "Taxas e Tarifas",
                                             "Telefone",
                                             "Terceiros",
                                             "Transferência entre contas",
                                             "Treinamentos",
                                             "Uniformes",
                                             "Vale Transporte",
                                             "Verbas Para Rescisão",
                                             "Vigilância e Monitoramento"
                                         ],
                              "tipos":  [
                                            "Tipo Transação",
                                            "Dinheiro",
                                            "Pix",
                                            "Cartão Crédito",
                                            "Transferência Bancária"
                                        ]
                          },
    "transactions":  [
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_11",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-08-01",
                             "uf":  "AGOSTO",
                             "fluxo":  "Entrada",
                             "categoria":  "Saldo Inicial",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  0,
                             "valor_liquido":  0,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_12",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-08-16",
                             "uf":  "AGOSTO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Compra caminhão - entrada",
                             "valor_nominal":  50000,
                             "valor_liquido":  -50000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_13",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-08-18",
                             "uf":  "AGOSTO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Compra Caminhão - saldo final",
                             "valor_nominal":  250000,
                             "valor_liquido":  -250000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_14",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-02",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Pagamento Tanque",
                             "valor_nominal":  7500,
                             "valor_liquido":  -7500,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_15",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-04",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Compra dominio de Site",
                             "valor_nominal":  364,
                             "valor_liquido":  -364,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_16",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-04",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Conserto feixe de molas - Volvo",
                             "valor_nominal":  1050,
                             "valor_liquido":  -1050,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_17",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-08",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Despachante execução ANTT",
                             "valor_nominal":  570,
                             "valor_liquido":  -570,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_18",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-08",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Geometria VOLVO",
                             "valor_nominal":  400,
                             "valor_liquido":  -400,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_19",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-09",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Elétrica VOLVO",
                             "valor_nominal":  825,
                             "valor_liquido":  -825,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_20",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-10",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Procuração",
                             "valor_nominal":  294.32,
                             "valor_liquido":  -294.32,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_21",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-19",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Compra Graxa Cobreada",
                             "valor_nominal":  3104.6,
                             "valor_liquido":  -3104.6,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_22",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-22",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Material + mão de obra - manutenção caminhão MLT6B00",
                             "valor_nominal":  1105,
                             "valor_liquido":  -1105,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_23",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-22",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Compra Produtos para perfuração",
                             "valor_nominal":  3986.38,
                             "valor_liquido":  -3986.38,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_24",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-22",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Pedágios VOLVO",
                             "valor_nominal":  38.8,
                             "valor_liquido":  -38.8,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_25",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-23",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Compra materiais salientes máquina Furo",
                             "valor_nominal":  3137.2,
                             "valor_liquido":  -3137.2,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_26",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-23",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Reposição Caixa Carlos, viagem busca tanque e transferência caminhão",
                             "valor_nominal":  2981.49,
                             "valor_liquido":  -2981.49,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_27",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-24",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "PAGTO ELETRON COBRANCA ENTRADA MAQUINA",
                             "valor_nominal":  100000,
                             "valor_liquido":  -100000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_28",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-29",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "500 diesel, 90 taxa, 475 aferição tacógrafo volvo",
                             "valor_nominal":  1065,
                             "valor_liquido":  -1065,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_29",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-09-30",
                             "uf":  "SETEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "DES: XCMG BRASIL INDUSTRIA 01/10",
                             "valor_nominal":  1350000,
                             "valor_liquido":  -1350000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_30",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-01",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Custo rastreador",
                             "valor_nominal":  172.64,
                             "valor_liquido":  -172.64,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_31",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-02",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Gasto transporte peças São Paulo",
                             "valor_nominal":  600,
                             "valor_liquido":  -600,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_32",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-02",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "CAIXA CARLOS",
                             "valor_nominal":  4000,
                             "valor_liquido":  -4000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_33",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-02",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Pagamento final Misturador MND",
                             "valor_nominal":  17500,
                             "valor_liquido":  -17500,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_34",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-02",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Certificado digital",
                             "valor_nominal":  210,
                             "valor_liquido":  -210,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_35",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-03",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Seguro caminhao",
                             "valor_nominal":  803.36,
                             "valor_liquido":  -803.36,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_36",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-06",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Compra Borracha limpa barra",
                             "valor_nominal":  560,
                             "valor_liquido":  -560,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_37",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-06",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Alteração de contrato",
                             "valor_nominal":  197.5,
                             "valor_liquido":  -197.5,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_38",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-08",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Custos salários",
                             "valor_nominal":  23500,
                             "valor_liquido":  -23500,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_39",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-08",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Frente material perfurações",
                             "valor_nominal":  177.5,
                             "valor_liquido":  -177.5,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_40",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-08",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Entrada metade uniformes",
                             "valor_nominal":  2060,
                             "valor_liquido":  -2060,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_41",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-09",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Conserto ar condicionado caminhão 1/3",
                             "valor_nominal":  1400,
                             "valor_liquido":  -1400,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_42",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-10",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Reposição de caixa e Caixa para OBRAS",
                             "valor_nominal":  20000,
                             "valor_liquido":  -20000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_43",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-14",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Compras sintas para máquina",
                             "valor_nominal":  775.96,
                             "valor_liquido":  -775.96,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_44",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-14",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Rastreador caminhão",
                             "valor_nominal":  72.22,
                             "valor_liquido":  -72.22,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_45",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-14",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Compra conexão  fns",
                             "valor_nominal":  112.97,
                             "valor_liquido":  -112.97,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_46",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-14",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Janta Carlos Felipe",
                             "valor_nominal":  70,
                             "valor_liquido":  -70,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_47",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-17",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Insulfilm Máquina Perfuratriz",
                             "valor_nominal":  880,
                             "valor_liquido":  -880,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_48",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-17",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Parcela truck Sinos plataforma",
                             "valor_nominal":  1622.54,
                             "valor_liquido":  -1622.54,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_49",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-17",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Arte adesivo caminhão e maquina",
                             "valor_nominal":  250,
                             "valor_liquido":  -250,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_50",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-22",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Ativação número Chave whatsapp",
                             "valor_nominal":  15,
                             "valor_liquido":  -15,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_51",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-24",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Caixa CARLOS",
                             "valor_nominal":  6500,
                             "valor_liquido":  -6500,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_52",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-10-30",
                             "uf":  "OUTUBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Metade uniformes",
                             "valor_nominal":  2285,
                             "valor_liquido":  -2285,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_53",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-01",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Entrada peça Válvula corta água",
                             "valor_nominal":  2000,
                             "valor_liquido":  -2000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_54",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-04",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Hospedagem Site três anos",
                             "valor_nominal":  355.51,
                             "valor_liquido":  -355.51,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_55",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-05",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Compra Borrachas Barras",
                             "valor_nominal":  582,
                             "valor_liquido":  -582,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_56",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-06",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Compra de fluido de perfuração para máquina mnd",
                             "valor_nominal":  2631.9,
                             "valor_liquido":  -2631.9,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_57",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-06",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Parte final válvula água Maquina",
                             "valor_nominal":  1850,
                             "valor_liquido":  -1850,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_58",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-07",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Salários TecnoDrill",
                             "valor_nominal":  25300,
                             "valor_liquido":  -25300,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_59",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-11",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Filtros máquina de mnd",
                             "valor_nominal":  1000,
                             "valor_liquido":  -1000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_60",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-11",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Caixa Carlos",
                             "valor_nominal":  25000,
                             "valor_liquido":  -25000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_61",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-11",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Contabilidade",
                             "valor_nominal":  450,
                             "valor_liquido":  -450,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_62",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-12",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Passagem Carlos rs",
                             "valor_nominal":  261.81,
                             "valor_liquido":  -261.81,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_63",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-13",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Recarga número TecnoDrill",
                             "valor_nominal":  15,
                             "valor_liquido":  -15,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_64",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-13",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Ativação Conta Sicoob TecnoDrill",
                             "valor_nominal":  100,
                             "valor_liquido":  -100,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_65",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-14",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Parcela final Truck Sinos",
                             "valor_nominal":  1622.54,
                             "valor_liquido":  -1622.54,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_66",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-15",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "roca filtros Máquina",
                             "valor_nominal":  350,
                             "valor_liquido":  -350,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_67",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-18",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Rastreadores",
                             "valor_nominal":  85.34,
                             "valor_liquido":  -85.34,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_68",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-18",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Alteração contratos",
                             "valor_nominal":  818,
                             "valor_liquido":  -818,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_69",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-19",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Projeto Água PAE",
                             "valor_nominal":  11.8,
                             "valor_liquido":  -11.8,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_70",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-24",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  30000,
                             "valor_liquido":  -30000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_71",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-24",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Caixa Felipe......",
                             "valor_nominal":  1200,
                             "valor_liquido":  -1200,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_72",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-24",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Caixa CARLOS",
                             "valor_nominal":  16000,
                             "valor_liquido":  -16000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_73",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-24",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Caixa Nilton Talaska",
                             "valor_nominal":  600,
                             "valor_liquido":  -600,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_74",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-11-27",
                             "uf":  "NOVEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Entrada Conserto Rampa Volvo",
                             "valor_nominal":  3500,
                             "valor_liquido":  -3500,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_75",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-12-05",
                             "uf":  "DEZEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  23500,
                             "valor_liquido":  -23500,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_76",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-12-12",
                             "uf":  "DEZEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Caixa Carlos",
                             "valor_nominal":  8000,
                             "valor_liquido":  -8000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_77",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2025-12-13",
                             "uf":  "DEZEMBRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Recarga whatsapp",
                             "valor_nominal":  15,
                             "valor_liquido":  -15,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_78",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-01-09",
                             "uf":  "JANEIRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  23500,
                             "valor_liquido":  -23500,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_79",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-01-14",
                             "uf":  "JANEIRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  25000,
                             "valor_liquido":  -25000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_80",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-02-04",
                             "uf":  "FEVEREIRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  100000,
                             "valor_liquido":  -100000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_81",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-02-13",
                             "uf":  "FEVEREIRO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  25000,
                             "valor_liquido":  -25000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_82",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-03-02",
                             "uf":  "MARÇO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Empréstimo Tecnodrill",
                             "valor_nominal":  600000,
                             "valor_liquido":  -600000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_83",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-03-03",
                             "uf":  "MARÇO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Empréstimo 2 para TECNODRILL",
                             "valor_nominal":  550000,
                             "valor_liquido":  -550000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_84",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-03-06",
                             "uf":  "MARÇO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  50000,
                             "valor_liquido":  -50000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_85",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-03-06",
                             "uf":  "MARÇO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  20000,
                             "valor_liquido":  -20000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_86",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-03-06",
                             "uf":  "MARÇO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  22000,
                             "valor_liquido":  -22000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_87",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-03-10",
                             "uf":  "MARÇO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  45000,
                             "valor_liquido":  -45000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_88",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-03-11",
                             "uf":  "MARÇO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Pagamento cintas caminhão daff",
                             "valor_nominal":  1175.56,
                             "valor_liquido":  -1175.56,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_89",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-03-12",
                             "uf":  "MARÇO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  170000,
                             "valor_liquido":  -170000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_90",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-03-12",
                             "uf":  "MARÇO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Custo retirada material RJ/sp",
                             "valor_nominal":  2000,
                             "valor_liquido":  -2000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_91",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-03-13",
                             "uf":  "MARÇO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  15000,
                             "valor_liquido":  -15000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_92",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-03-20",
                             "uf":  "MARÇO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  15000,
                             "valor_liquido":  -15000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_93",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-03-25",
                             "uf":  "MARÇO",
                             "fluxo":  "Entrada",
                             "categoria":  "Cobranças",
                             "descricao":  "EQUIPE AZUL CONSTRUTORA",
                             "valor_nominal":  73920,
                             "valor_liquido":  73920,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_94",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-03-26",
                             "uf":  "MARÇO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  0.01,
                             "valor_liquido":  -0.01,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_95",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-04-13",
                             "uf":  "ABRIL",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  12000,
                             "valor_liquido":  -12000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_96",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-04-14",
                             "uf":  "ABRIL",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  50000,
                             "valor_liquido":  -50000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_97",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-04-15",
                             "uf":  "ABRIL",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  15000,
                             "valor_liquido":  -15000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_98",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-04-23",
                             "uf":  "ABRIL",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  6500,
                             "valor_liquido":  -6500,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_99",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-04-28",
                             "uf":  "ABRIL",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  6000,
                             "valor_liquido":  -6000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_100",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-04-29",
                             "uf":  "ABRIL",
                             "fluxo":  "Entrada",
                             "categoria":  "Cobranças",
                             "descricao":  "EQUIPE AZUL CONSTRUTORA",
                             "valor_nominal":  84288,
                             "valor_liquido":  84288,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_101",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-05-11",
                             "uf":  "MAIO",
                             "fluxo":  "Entrada",
                             "categoria":  "Cobranças",
                             "descricao":  "EQUIPE AZUL CONSTRUTORA",
                             "valor_nominal":  32076,
                             "valor_liquido":  32076,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_102",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-05-14",
                             "uf":  "MAIO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  40000,
                             "valor_liquido":  -40000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_103",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-05-25",
                             "uf":  "MAIO",
                             "fluxo":  "Entrada",
                             "categoria":  "Cobranças",
                             "descricao":  "EQUIPE AZUL CONSTRUTORA",
                             "valor_nominal":  147720,
                             "valor_liquido":  147720,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_104",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-06-05",
                             "uf":  "JUNHO",
                             "fluxo":  "Entrada",
                             "categoria":  "Cobranças",
                             "descricao":  "SUL CONECT FIBRA",
                             "valor_nominal":  20572.34,
                             "valor_liquido":  20572.34,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_105",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-06-22",
                             "uf":  "JUNHO",
                             "fluxo":  "Entrada",
                             "categoria":  "Cobranças",
                             "descricao":  "EFICAZ ENGENHARIA",
                             "valor_nominal":  2700,
                             "valor_liquido":  2700,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_106",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-06-25",
                             "uf":  "JUNHO",
                             "fluxo":  "Entrada",
                             "categoria":  "Cobranças",
                             "descricao":  "EQUIPE AZUL CONSTRUTORA",
                             "valor_nominal":  100224,
                             "valor_liquido":  100224,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_107",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-06-23",
                             "uf":  "JUNHO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  35000,
                             "valor_liquido":  -35000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_108",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-07-10",
                             "uf":  "JULHO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  25000,
                             "valor_liquido":  -25000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_109",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-07-14",
                             "uf":  "JULHO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  56000,
                             "valor_liquido":  -56000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_110",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-07-16",
                             "uf":  "JULHO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  3000,
                             "valor_liquido":  -3000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_111",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-07-17",
                             "uf":  "JULHO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  15000,
                             "valor_liquido":  -15000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_112",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-07-20",
                             "uf":  "JULHO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  15000,
                             "valor_liquido":  -15000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_113",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-07-21",
                             "uf":  "JULHO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  15000,
                             "valor_liquido":  -15000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_114",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-07-22",
                             "uf":  "JULHO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  11000,
                             "valor_liquido":  -11000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_115",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-07-24",
                             "uf":  "JULHO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  10000,
                             "valor_liquido":  -10000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_116",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-07-27",
                             "uf":  "JULHO",
                             "fluxo":  "Entrada",
                             "categoria":  "Cobranças",
                             "descricao":  "EQUIPE AZUL CONSTRUTORA",
                             "valor_nominal":  83784,
                             "valor_liquido":  83784,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_117",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-07-27",
                             "uf":  "JULHO",
                             "fluxo":  "Entrada",
                             "categoria":  "Cobranças",
                             "descricao":  "EQUIPE AZUL CONSTRUTORA",
                             "valor_nominal":  133500,
                             "valor_liquido":  133500,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_118",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-08-14",
                             "uf":  "AGOSTO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  50000,
                             "valor_liquido":  -50000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_119",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-08-20",
                             "uf":  "AGOSTO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  15000,
                             "valor_liquido":  -15000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         },
                         {
                             "id":  "FLUXO_TECNODRILL_X_JLE_120",
                             "banco":  "SICOOB",
                             "aba":  "FLUXO TECNODRILL X JLE",
                             "remessa":  "MANUAL",
                             "competencia":  "N/D",
                             "data":  "2026-08-21",
                             "uf":  "AGOSTO",
                             "fluxo":  "Saída",
                             "categoria":  "TecnoDrill",
                             "descricao":  "Transferência entre contas",
                             "valor_nominal":  15000,
                             "valor_liquido":  -15000,
                             "meio_pagamento":  "Pix",
                             "is_transfer":  false
                         }
                     ]
};
